apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ include "ld-relay.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ld-relay.name" . }}
    helm.sh/chart: {{ include "ld-relay.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  prodkey: {{ .Values.ldProdKey | b64enc | quote }}
  testkey: {{ .Values.ldTestKey | b64enc | quote }}
