apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ include "ld-relay.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "ld-relay.name" . }}
    helm.sh/chart: {{ include "ld-relay.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $index, $map := .Values.ldEnv }}
{{- range $name, $val := $map }}
  {{ $name }}sdkKey: {{ $val.sdkKey | b64enc | quote }}
{{- if $val.mobileKey }}
  {{ $name }}mobileKey: {{ $val.mobileKey | b64enc | quote }}
{{- end }}
{{- if $val.clientSideId }}
  {{ $name }}clientSideId: {{ $val.clientSideId | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
